export default {
  admission: "fa-file-medical",
  cancel: "fa-times",
  check: "fa-check",
  checkCircle: "fa-check-circle",
  delete: "fa-trash-alt",
  discharge: "fa-file-medical-alt",
  edit: "fa-pencil-alt",
  health: "fa-heartbeat",
  hospital: "fa-hospital-symbol",
  patient: "fa-user-injured",
  save: "fa-save",
  search: "fa-search",
  times: "fa-times",
  timesCircle: "fa-times-circle",
  transfer: "fa-exchange-alt",
  treatment: "fa-procedures",
};
